patch:
    menu/page_size: 9
    schema_list:
      - schema: luna_pinyin_simp
      - schema: double_pinyin_flypy
    translator/dictionary: luna_pinyin.extended
    # app_options: # Not Working!
    #     gnome-terminal:
    #         ascii_mode: true
    #     code:
    #         ascii_mode: true
    # translator/enable_correction: true
    ascii_composer/switch_key:
        Shift_L: commit_code 
        Shift_R: noop
    switches/@0/reset: 1
